name: ci

on:
  pull_request:
    types: [ opened, synchronize ]
  push:
    branches: [ main ]

jobs:
  ci:
    runs-on: codebuild-databricks-example-${{ github.run_id }}-${{ github.run_attempt }}
    environment: test
    steps:
      - run: echo "Hello World"
#      - uses: actions/checkout@v4
#      - uses: databricks/setup-cli@main
#      - name: Set up Python
#        uses: actions/setup-python@v5
#        with:
#          python-version: '3.10'
#          cache: 'pip'
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install hatch
#      - name: Lint
#        run: hatch run lint:style .
#      - name: Unit tests
#        run: hatch run test-cov